---

# mjuenema.lxc/tasks/install_from_git.yml

# Install from Git
#

# TODO: set some facts based on lxc_configure_*
#       - lxc_network_link

- name: "Install LXC build dependencies"
  yum: name="{{ item }}"
  with_items: "{{ lxc_build_dependencies }}"
  when: lxc_install_from_git == True

- name: "Set random UUID"
  set_fact: random_uuid="{{ ansible_date_time.iso8601_micro | to_uuid }}"
  when: lxc_install_from_git == True

- name: "Show random UUID"
  debug: msg="{{ random_uuid }}"
  when: lxc_install_from_git == True

- name: "Clone LXC Git repository"
  git: name="{{ lxc_git_url }}"
       dest="/tmp/{{ random_uuid }}"
  when: lxc_install_from_git == True

- name: "Run autogen.sh"
  command: ./autogen.sh creates=configure chdir="/tmp/{{ random_uuid }}"

- name: "Run configure.sh"
  command: ./configure creates=Makefile chdir="/tmp/{{ random_uuid }}"

