---

# mjuenema.lxc/tasks/Redhat.yml


# Install from packages
#
- name: "Install LXC packages"
  yum: name="{{ item }}"
  with_items: "{{ lxc_packages }}"
  when: lxc_install_from_git == False

- name: "Enable and start libvirtd"
  service: name=libvirtd
           state=started
           enabled=yes
  when: lxc_install_from_git == False
